project_path: '/jupyter/FloodEvacPlanner'
input_path: 'input'
output_path: 'output'
logs_path: 'logs'
shp_files:
  spaces: 'space02.shp'
  shelters: 'shelter_plan01.shp'
  map: 'map01.shp'
  buildings: 'building01.shp'
  rivers: 'river01.shp'
  roads: 'network01.shp'
  road_nodes: 'network_node01.shp'
  floods: '100yy01.shp'
gml_files:
  graph: 'graph_0.gml'
  flooded_graph: 'graph_100.gml'
tags:
  flood_tag: '100'
  shelter_tag: 'plan01'
random_seed: 2025