#project_path: '/jupyter/FloodEvacPlanner'
project_path: 'D:\coding\FloodEvacPlanner'
input_path: 'input'
output_path: 'output'
logs_path: 'logs'

tags:
  flood_tag: '1974'
  crash_tag: 'low'
  traffic_tag: 'wd_am_off_peak'

algos:
  algo1: 'dijkstra'           # dijkstra, astar
  algo2: 'dijkstra'           # dijkstra, astar
  algo3: 'multi-dijkstra'     # multi-dijkstra, rrt-prm
  weight1: 'time'             # time, length
  weight2: 'length'           # time, length
  weight3: 'length'           # time, length

files:
  edges_all: 'Edges.shp'
  edges_flood: 'edges_197401.shp' # align with flood_tag
  crash: 'crash.shp'
  traffic: 'destinations_wd_am_off_peak.shp' # align with traffic_tag
  shelter: 'shelter_snap.shp'

params:
  crash_ratio: 0.1            # align with crash_tag
  max_ped: 5000
  max_shelter: 3000
  random_seed: 2025
  sample_size: 200
  max_replan: 10
  visualize: true            # HTML