#project_path: '/jupyter/FloodEvacPlanner'
project_path: 'D:\coding\FloodEvacPlanner'
input_path: 'input'
output_path: 'output'
logs_path: 'logs'

tasks_id: '720_plan'
tasks: 
#  LOAD_ENV: true
#  VIS_ENV: true
#  RUN_ALGO: 'Dijkstra'
  VIS_ROUTE: true
  ANALYZE_ROUTE: true

shp_files:
  map: 'map01.shp'
  buildings: 'building01.shp'
  rivers: 'river01.shp'
  floods: '720yy.shp' # align with flood_tag

  roads: 'network03_v2.shp'
  road_nodes: 'network_node04.shp'

gml_files:
  graph: 'graph_0.gml'
  flooded_graph: 'graph_720.gml' # align with floods

tags:
  flood_tag: '720' # align with floods
  shelter_tag: 'plan' # plan / zz

random_seed: 2025